SHELL=/bin/bash
MAKEFILE = makefile
SRC = src
GEN = generated
INC =
INC+= inc
INC+= $(GEN)
INC+= imgui/src
INC+= resources/generated_src
OBJ = obj
BIN = bin
DEP = dep
CXXC= g++
GENERATOR = recreated_goon/bin/generator

CXXFLAGS = $(addprefix -I,$(INC))
CXXFLAGS+= -std=c++20
CXXFLAGS+= -O3
#CXXFLAGS+= -s
#CXXFLAGS+= -march=native
CXXFLAGS+= -pedantic
CXXFLAGS+= -Wfatal-errors
CXXFLAGS+= -pthread
# CXXFLAGS+= -flto

# CXXFLAGS+= -ggdb
# CXXFLAGS+= -fsanitize=address
# CXXFLAGS+= -fsanitize=thread

CXXFLAGS_SO=$(CXXFLAGS)
CXXFLAGS_SO+= -fPIC


ifeq ($(CXXC),clang++)
CXXFLAGS+= -stdlib=libc++
OBJ=obj_clang++
BIN=bin_clang++
DEP=dep_clang++
endif



LIBS =
LIBS+= SDL2
LIBS+= SDL2_ttf
LIBS+= SDL2_image
LIBS+= GLEW
LIBS+= GL
LIBS+= GLU

LFLAGS = $(addprefix -l,$(LIBS))

